// <auto-generated />
using Microservices.ProductAPI.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Microservices.ProductAPI.Migrations
{
    [DbContext(typeof(BancoContext))]
    [Migration("20240628184143_PopulandoTbaleProdutos")]
    partial class PopulandoTbaleProdutos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microservices.ProductAPI.Data.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Camisa",
                            Price = 10.99m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Calça",
                            Price = 19.99m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Bermuda",
                            Price = 29.50m
                        },
                        new
                        {
                            Id = 4,
                            Name = "Moletom",
                            Price = 109.99m
                        },
                        new
                        {
                            Id = 5,
                            Name = "Boné",
                            Price = 17.90m
                        },
                        new
                        {
                            Id = 6,
                            Name = "Camiseta",
                            Price = 14.99m
                        },
                        new
                        {
                            Id = 7,
                            Name = "Chapéu",
                            Price = 39.99m
                        },
                        new
                        {
                            Id = 8,
                            Name = "Meia",
                            Price = 9.99m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
